import { pool } from '../db.js';
import { getAuctionById, type AuctionDTO } from './getAuction.js';
import { placeBidAndAnnounce } from './placeBidAndAnnounce.js';

/**
 * A single, known, findable-by-title auction that hackathon demos reset
 * to a clean state before each run — see docs/09-demo-runbook.md. Not a
 * UUID hardcoded anywhere (auction ids are generated by Postgres); found
 * or created by this exact title instead, the same "find by a stable
 * human name" pattern users already use (backend/src/routes/users.ts).
 */
const DEMO_AUCTION_TITLE = 'NeuraBid Live Demo Auction';
const DEMO_STARTING_PRICE = 100;
const DEMO_MIN_INCREMENT = 5;
const DEMO_DURATION_MINUTES = 15;

const DEMO_BOT_USERNAME_PREFIX = 'demo_bot_';

/**
 * Resets the demo auction to a known, clean starting state: zero bids,
 * current_price back to starting_price, status active, a fresh ends_at
 * so a countdown timer always has real time left. Deletes any bids the
 * demo auction accumulated from a previous run — deliberately, and only
 * for this one specifically-named auction, never anything else in the
 * database (see docs/09-demo-runbook.md for why a full reseed isn't
 * used here: it would also delete every user account, forcing everyone
 * watching to log in again mid-demo).
 */
export async function resetDemoAuction(): Promise<AuctionDTO> {
  const client = await pool.connect();
  try {
    await client.query('BEGIN');

    const { rows: existing } = await client.query<{ id: string }>(
      'SELECT id FROM auctions WHERE title = $1',
      [DEMO_AUCTION_TITLE],
    );

    let auctionId: string;
    if (existing[0]) {
      auctionId = existing[0].id;
      // current_bid_id must be cleared BEFORE deleting the bid rows it
      // might point at — auctions.current_bid_id has a foreign key onto
      // bids(id), so deleting a still-referenced bid first violates that
      // constraint. This exact ordering bug was caught by
      // routes.demo.test.ts on its first run.
      await client.query('UPDATE auctions SET current_bid_id = NULL WHERE id = $1', [auctionId]);
      await client.query('DELETE FROM bids WHERE auction_id = $1', [auctionId]);
      await client.query(
        `UPDATE auctions
         SET current_price = $1, min_increment = $2, status = 'active',
             starts_at = now(),
             ends_at = now() + make_interval(mins => $3)
         WHERE id = $4`,
        [DEMO_STARTING_PRICE, DEMO_MIN_INCREMENT, DEMO_DURATION_MINUTES, auctionId],
      );
    } else {
      const { rows } = await client.query<{ id: string }>(
        `INSERT INTO auctions (title, description, starting_price, current_price, min_increment, status, starts_at, ends_at)
         VALUES ($1, $2, $3, $3, $4, 'active', now(), now() + make_interval(mins => $5))
         RETURNING id`,
        [
          DEMO_AUCTION_TITLE,
          'Reset before every demo run — see docs/09-demo-runbook.md.',
          DEMO_STARTING_PRICE,
          DEMO_MIN_INCREMENT,
          DEMO_DURATION_MINUTES,
        ],
      );
      auctionId = rows[0].id;
    }

    await client.query('COMMIT');

    const auction = await getAuctionById(auctionId);
    if (!auction) throw new Error('Demo auction vanished immediately after reset — this should be impossible');
    return auction;
  } catch (err) {
    await client.query('ROLLBACK').catch(() => {});
    throw err;
  } finally {
    client.release();
  }
}

export async function getDemoAuction(): Promise<AuctionDTO | null> {
  const { rows } = await pool.query<{ id: string }>('SELECT id FROM auctions WHERE title = $1', [
    DEMO_AUCTION_TITLE,
  ]);
  if (!rows[0]) return null;
  return getAuctionById(rows[0].id);
}

async function getOrCreateDemoBotUser(index: number): Promise<string> {
  const username = `${DEMO_BOT_USERNAME_PREFIX}${index}`;
  const {
    rows: [user],
  } = await pool.query<{ id: string }>(
    `INSERT INTO users (username) VALUES ($1)
     ON CONFLICT (username) DO UPDATE SET username = EXCLUDED.username
     RETURNING id`,
    [username],
  );
  return user.id;
}

export interface SimulationResult {
  requested: number;
  accepted: number;
  rejected: number;
  results: { userId: string; status: 'accepted' | 'rejected'; amount: number; message?: string }[];
}

/**
 * Fires `count` real, genuinely-concurrent bids at the demo auction using
 * real demo-bot user accounts (always named demo_bot_N — visually obvious
 * in the bid history and live stream as generated, not a real bidder) and
 * the real placeBid() function — the exact same code path a real bidder
 * hits, just triggered on demand instead of by a real click. Every one of
 * these bids is real; the only thing "simulated" is that a script, not a
 * human, decided to press the button `count` times at once. See
 * docs/09-demo-runbook.md for how this is labeled during a live demo.
 */
export async function simulateConcurrentBids(count: number): Promise<SimulationResult> {
  const demoAuction = await getDemoAuction();
  if (!demoAuction) {
    throw new Error('Demo auction does not exist yet — call resetDemoAuction() first');
  }

  const userIds = await Promise.all(
    Array.from({ length: count }, (_, i) => getOrCreateDemoBotUser(i)),
  );

  // Every bot targets an amount just above the CURRENT price at the
  // moment the simulation was requested — a deliberately tight race, so
  // most of them collide and only one (at most) can win. This is what
  // makes Demo B a genuine, visible demonstration of the row lock, not a
  // guaranteed-success scripted sequence.
  const targetAmount = demoAuction.currentPrice + demoAuction.minIncrement;

  // placeBidAndAnnounce() (shared with the real HTTP bid route) records
  // metrics and broadcasts identically to a real bid — the only thing
  // that marks these as simulated is the demo_bot_ username, which is
  // the point: honest, visible labeling, not a fake code path.
  const settled = await Promise.allSettled(
    userIds.map((userId) => placeBidAndAnnounce(demoAuction.id, userId, targetAmount)),
  );

  const results = settled.map((outcome, i) => {
    if (outcome.status === 'fulfilled') {
      return { userId: userIds[i], status: 'accepted' as const, amount: outcome.value.amount };
    }
    const message = outcome.reason instanceof Error ? outcome.reason.message : 'Unknown error';
    return { userId: userIds[i], status: 'rejected' as const, amount: targetAmount, message };
  });

  return {
    requested: count,
    accepted: results.filter((r) => r.status === 'accepted').length,
    rejected: results.filter((r) => r.status === 'rejected').length,
    results,
  };
}

export { DEMO_AUCTION_TITLE, DEMO_BOT_USERNAME_PREFIX };
